<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_VERSION' => '0.4.2',
  'APP_SECRET' => '91739cd3f0af5ce014a7db0d451160e2805aa31b',
);
